name: CMake

on:
  push:
    branches: [ feature/mjmagee991/github-builds ]
  pull_request:
    branches: [ main ]

env:
  GCC_ARM_TOOLS_PATH: /usr/bin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Compiler and Linter
        run: |
          sudo apt-get install gcc-arm-none-eabi
          sudo apt-get install clang-format-12
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-12 10000

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Apply Formatting
        run: |
          cmake --build ${{github.workspace}}/build --target clang-format
          if git diff-files --quiet; then
            echo 'No formatting changes'
          else
            echo 'Formatting changes applied:'
            git diff --raw
            git config --global user.email "N/A"
            git config --global user.name "GitHub Build"
            git commit -a -m "Applied Formatting Changes During GitHub Build"
            git push origin
          fi

    # git commit -a -m "Applied clang-format Formatting" && git push origin
