name: Create Sample Builds

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# Set necessary environment variables
env:
  GCC_ARM_TOOLS_PATH: /usr/bin

permissions:
  contents: read

jobs:
  build-backend:
    name: Build EVT-Core Samples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
      
      - name: Install Compiler and Linter
        run: |
          sudo apt-get install gcc-arm-none-eabi
          sudo apt-get install clang-format-15
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-15 10000

      - name: F302 Debug Build
        run: |
          cmake -DTARGET_DEV=STM32F302x8 -B ${{github.workspace}}/build/f302/debug
          cmake --build ${{github.workspace}}/build/f302/debug

      - name: F302 Release Build
        run: |
          cmake -DTARGET_DEV=STM32F302x8 -DCMAKE_BUILD_TYPE RELEASE -B ${{github.workspace}}/build/f302/release
          cmake --build ${{github.workspace}}/build/f302/release

      - name: F334 Debug Build
        run: |
          cmake -DTARGET_DEV=STM32F334x8 -B ${{github.workspace}}/build/f334/debug
          cmake --build ${{github.workspace}}/build/f334/debug

      - name: F334 Release Build
        run: |
          cmake -DTARGET_DEV=STM32F334x8 -B -D CMAKE_BUILD_TYPE RELEASE ${{github.workspace}}/build/f334/release
          cmake --build ${{github.workspace}}/build/f334/release
          
      - name: F446 Debug Build
        run: |
          cmake -DTARGET_DEV=STM32F446xx -B ${{github.workspace}}/build/f446/debug
          cmake --build ${{github.workspace}}/build/f446/debug
           
      - name: F446 Release Build
        run: |
          cmake -DTARGET_DEV=STM32F446xx --D CMAKE_BUILD_TYPE RELEASE B ${{github.workspace}}/build/f446/release
          cmake --build ${{github.workspace}}/build/f446/release
          
      - name: Upload f203 Debug Samples
        uses: actions/upload-artifact@v6
        with:
          name: samples-f203-debug
          path: |
            ${{github.workspace}}/build/f302/debug/samples/**/*.bin
            !CmakeFiles

      - name: Upload f203 Release Samples
        uses: actions/upload-artifact@v6
        with:
          name: samples-f203-release
          path: |
            ${{github.workspace}}/build/f302/release/samples/**/*.bin
            !CmakeFiles
            
      - name: Upload f334 Debug Samples
        uses: actions/upload-artifact@v6
        with:
          name: samples-f334-debug
          path: |
            ${{github.workspace}}/build/f334/debug/samples/**/*.bin            
            !CMakeFiles
            
      - name: Upload f334 Release Samples
        uses: actions/upload-artifact@v6
        with:
          name: samples-f334-release
          path: |
            ${{github.workspace}}/build/f334/release/samples/**/*.bin            
            !CMakeFiles
            
      - name: Upload f446 Samples
        uses: actions/upload-artifact@v6
        with:
          name: samples-f446-debug
          path: |
            ${{github.workspace}}/build/f446/debug/samples/**/*.bin
            !CmakeFiles
            
      - name: Upload f446 Release Samples
        uses: actions/upload-artifact@v6
        with:
          name: samples-f446-release
          path: |
            ${{github.workspace}}/build/f446/release/samples/**/*.bin
            !CmakeFiles
